# Configuration YAML for APP

# Enable OAuth
ENABLE_OAUTH: True

# App metadata
PROJECT_ID: genai-dnb-demo
LOCATION: global
VIDEO_BUCKET_NAME: 504683450406-veo-generation
SECRET_ID: veo-oauth-secret

# FRONTEND_URL: https://veo.vc7.info
# REDIRECT_URI: https://veo.vc7.info/auth
FRONTEND_URL: http://localhost:7860
REDIRECT_URI: http://localhost:7860/auth

ALLOWED_DOMAINS:
  - google.com
  - vwmc.altostrat.com

# Role-Based Access Control
COST_MANAGERS:
  - vwmc@google.com

APP_ADMINS:
  - vwmc@google.com

# Analysis result (BigQuery)
ENABLE_BIGQUERY_LOGGING: True
ANALYSIS_DATASET: marketing_materials_analysis
HISTORY_TABLE: veo_history

# Logging
LOGGER_NAME: veo.service
LOGGING_FORMAT: "%(asctime)s [%(levelname)s]: %(message)s"

# Prompt Gallery
PROMPT_GALLERY_DB: prompt-gallery
PROMPT_GALLERY_COLLECTION: prompts

# Configuration
CONFIG_DB: "veo-app-config"

# Notification Banner
# Set a list of messages here to display banners to all users.
# An empty list will hide the banner.
BANNER_MESSAGES:
  - "Veo3 Image-2-Video in current Argolis project is infeasible."
  - "A new model 'veo-3.0-generate-preview' is now available for testing."
