# Enable OAuth
ENABLE_OAUTH: True

# App metadata
PROJECT_ID: genai-dnb-demo
LOCATION: global
VIDEO_BUCKET_NAME: 504683450406-veo-generation
SECRET_ID: veo-oauth-secret

GEMINI_MODEL: 'gemini-2.5-flash-preview-09-2025'

# FRONTEND_URL: https://veo.vc7.info
# REDIRECT_URI: https://veo.vc7.info/auth
FRONTEND_URL: http://localhost:7860
REDIRECT_URI: http://localhost:7860/auth

ALLOWED_DOMAINS:
  - google.com
  - vwmc.altostrat.com

# Role-Based Access Control
COST_MANAGERS:
  - vwmc@google.com

APP_ADMINS:
  - vwmc@google.com

# Analysis result (BigQuery)
ENABLE_BIGQUERY_LOGGING: True
ANALYSIS_DATASET: marketing_materials_analysis
HISTORY_TABLE: veo_history
IMAGEN_HISTORY_TABLE: imagen_history
IMAGE_ENRICHMENT_HISTORY_TABLE: image_enrichment_history
BIGQUERY_LOCATION: us-central1

# Logging
LOGGER_NAME: veo.service
LOGGING_FORMAT: "%(asctime)s [%(levelname)s]: %(message)s"

# Prompt Gallery
PROMPT_GALLERY_DB: veo-prompt-gallery
PROMPT_GALLERY_COLLECTION: prompts

# Groups
GROUPS_DB: veo-app-user-groups

# Creative Projects
CREATIVE_PROJECTS_DB: veo-creative-projects

# Video Sharing
SHARED_VIDEOS_DB: veo-app-shared-videos
SHARED_VIDEOS_COLLECTION: shared_videos

# Configuration
CONFIG_DB: "veo-app-config"

# Similarity Search Config
FIND_SIMILAR_IMAGES_IMAGEN_HISTORY: FindSimilarImages_ImagenHistory
FIND_SIMILAR_IMAGES_IMAGE_ENRICHMENT_HISTORY: FindSimilarImages_EnrichmentHistory
FIND_SIMILAR_VIDEOS_VEO_HISTORY: FindSimilarVideos_VeoHistory
FIND_SIMILAR_TOP_K: 10

# Multimodal Embedding Model Location
LOCATION_MULTIMODAL_EMBEDDING_MODEL: "us-central1"

# Max Worker Count
MAX_WORKER_COUNT: 6

# Notification Banner
# Set a list of messages here to display banners to all users.
# An empty list will hide the banner.
BANNER_MESSAGES:
  - "Veo3 & Imagen 4 series are ready"
  - "Veo3 16:9 & 9:16 are ready"
  - "Gemini 2.5 Flash Image (nano-banana) is ready"
