models:
  - id: "imagen-4.0-ultra-generate-001"
    name: "Imagen 4 Ultra"
    type: "imagen-4.0"
    pricing:
      - effective_date: "2025-01-01"
        per_image: 0.06
      - effective_date: "2025-10-01"
        per_image: 0.06
  - id: "imagen-4.0-generate-001"
    name: "Imagen 4"
    type: "imagen-4.0"
    pricing:
      - effective_date: "2025-01-01"
        per_image: 0.04
      - effective_date: "2025-10-01"
        per_image: 0.04
  - id: "imagen-4.0-fast-generate-001"
    name: "Imagen 4 Fast"
    type: "imagen-4.0"
    pricing:
      - effective_date: "2025-01-01"
        per_image: 0.02
      - effective_date: "2025-10-01"
        per_image: 0.02
