models:
  - id: "veo-2.0-generate-001"
    name: "Veo 2.0"
    type: "veo-2.0"
    pricing:
      - effective_date: "2025-01-01"
        video_with_audio: 0.50
        video_without_audio: 0.50
      - effective_date: "2025-10-01"
        video_with_audio: 0.50
        video_without_audio: 0.50
  - id: "veo-3.0-generate-preview"
    name: "Veo 3.0 Preview"
    type: "veo-3.0"
    pricing:
      - effective_date: "2025-01-01"
        video_with_audio: 0.75
        video_without_audio: 0.50
      - effective_date: "2025-09-01"
        video_with_audio: 0.40
        video_without_audio: 0.20
  - id: "veo-3.0-fast-generate-preview"
    name: "Veo 3.0 Fast Preview"
    type: "veo-3.0"
    pricing:
      - effective_date: "2025-01-01"
        video_with_audio: 0.40
        video_without_audio: 0.25
      - effective_date: "2025-09-01"
        video_with_audio: 0.15
        video_without_audio: 0.10
